[project]
name = "optimization-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyterlab>=4.3.6",
    "matplotlib>=3.10.1",
    "numba>=0.61",
    "numpy>=2",
    "pandas>=2.2.3",
    "scipy>=1.15.2",
]
